### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by nacho** [cyrusimap/cyrus-sasl#433] opened 2017-07-07 21:53 UTC
Hey Ken, any chance to get the final release?

**Comment by quanah** [comment] 2017-07-07 22:17
I sure hope it wouldn't be the final release ever.  But I've really seen no commitment from fastmail to keep cyrus-sasl going, just cyrus-imapd.  Does the cyrus-sasl project need a new home?  I may know some interested parties if so.

**Comment by brong** [comment] 2017-07-08 01:47
FastMail is keen for cyrus-sasl to keep being developed - we just have no specific need for changes to it for ourselves.
I'd love the interested parties to keep contributing.  The code is on github and with a very permissive license.
Cheers,

Bron.


On Sat, 8 Jul 2017, at 08:17, Quanah Gibson-Mount wrote:
> I sure hope it wouldn't be the final release ever.  But I've really seen no commitment from fastmail to keep cyrus-sasl going, just cyrus-imapd.  Does the cyrus-sasl project need a new home?  I may know some interested parties if so.> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2]. > 

--
  Bron Gondwana
  brong@fastmail.fm



Links:

  1. https://github.com/cyrusimap/cyrus-sasl/issues/433#issuecomment-313806019

**Comment by quanah** [comment] 2017-07-08 03:04
Hi @brong 
I appreciate the response, however, cyrus-sasl needs a dedicated team to maintain it.  It has been years since the previous release, which was extremely buggy.  Numerous people have made contributions back to the project that languish in github or as patches on the devel list, and have never been applied.  While you may not use cyrus-sasl, it is a core component for many open source projects, such as OpenLDAP and PostFix.  It also needs participation with other projects that it depends on, such as Heimdal Kerberos.  If Fastmail cannot dedicate the time and resources to cover everything that's necessary for it to move forward as viable software, I think it would be in the best interests of the community at large for it to be moved into a project separate from cyrus-imapd, where it is managed by those who make use of it.
Regards,
Quanah

**Comment by brong** [comment] 2017-07-08 03:52
Are you able to join the Cyrus development Hangout this Monday?  We're doing a planning meeting to discus the priorities for the project for the next few months, and it would be great to have somebody interested in putting work into SASL join that call.

On Sat, 8 Jul 2017, at 13:04, Quanah Gibson-Mount wrote:
> Hi @brong[1]
>  I appreciate the response, however, cyrus-sasl needs a dedicated team to maintain it.  It has been years since the previous release, which was extremely buggy.  Numerous people have made contributions back to the project that languish in github or as patches on the devel list, and have never been applied.  While you may not use cyrus-sasl, it is a core component for many open source projects, such as OpenLDAP and PostFix.  It also needs participation with other projects that it depends on, such as Heimdal Kerberos.  If Fastmail cannot dedicate the time and resources to cover everything that's necessary for it to move forward as viable software, I think it would be in the best interests of the community at large for it to be moved into a project separate from cyrus-imapd, where it is managed by those who make use of it.>  Regards,
>  Quanah


> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub[2], or mute the thread[3]. > 

--
  Bron Gondwana
  brong@fastmail.fm



Links:

  1. https://github.com/brong
  2. https://github.com/cyrusimap/cyrus-sasl/issues/433#issuecomment-313829496

**Comment by quanah** [comment] 2017-07-08 18:17
@brong sure, as long as it is a reasonable time for west coast United States. ;) I'll need the meeting info as well :)

**Comment by brong** [comment] 2017-07-09 01:46
Yeah, not really :(  Sorry.  We have to fit Australia and Europe in, so it's 4am for you.  Damn.  Let's schedule a separate Cyrus SASL call some time.
We're currently meeting in https://hangouts.google.com/hangouts/_/g4xnqjjb5zvomzeb4kqvja3fz4a at 11am GMT on Mondays.

On Sun, 9 Jul 2017, at 04:17, Quanah Gibson-Mount wrote:
> @brong[1] sure, as long as it is a reasonable time for west coast United States. ;) I'll need the meeting info as well :)> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub[2], or mute the thread[3]. > 

--
  Bron Gondwana
  brong@fastmail.fm



Links:

  1. https://github.com/brong
  2. https://github.com/cyrusimap/cyrus-sasl/issues/433#issuecomment-313872641

**Comment by ksmurchison** [comment] 2017-07-14 15:58
2.1.27 RC2 has been posted

**Comment by nacho** [comment] 2017-10-04 15:28
@ksmurchison how are we doing to make the final release? at some point we have to draw the line and just release, in the worse case we can always make a .28...

**Comment by ksmurchison** [comment] 2017-10-09 12:24
RC5 will be uploaded later today for a final check (mostly against PAM) and then I will make a final release

**Comment by quanah** [comment] 2017-10-09 14:59
@ksmurchison Even with the significant regression in #419 still present? The analysis done by @aamelnikov was incorrect, and there's been zero followup.

**Comment by ksmurchison** [comment] 2017-10-09 15:01
I will have Alexey review this again prior to final release.

**Comment by JanParcel** [comment] 2017-11-01 23:09
So, this regression #419 is not a regression from 2.1.26, it's a regression from 2.1.23?  So if I have customers using .26, and move to .27, there's no gssapi or ldap-related regression for them?

**Comment by quanah** [comment] 2017-11-01 23:17
@JanParcel It's probably not possible to know what regressions exist in 2.1.27 vs 2.1.26... but yes, 2.1.26 broke behavior that worked with 2.1.23 and prior.  #419 most often affects people who use Java JNDI LDAP clients.

**Comment by JanParcel** [comment] 2017-11-01 23:26
Thanks.  I meant no KNOWN regression, because a comment in the 2.1.27-rc5 notification concerned me:  "The biggest outstanding issues are those around recent GSSAPI changes."

**Comment by ksmurchison** [comment] 2017-11-24 15:04
Just had a chat with Alexey.  We are committed to resolving the GSSAPI issue(s) and any other non-invasive issues/pull-requests within the next month.  Probably one more (short-lived) release candidate with the final 2.1.27 released by Christmas.

**Comment by Jakuje** [comment] 2018-02-23 16:14
Two months later. Any update on release? I submitted the feedback on the GSSAPI issue and one more unrelated bug recently, but I would really like to get rid of old cruft of patches and have upstream release for next Fedora.

**Comment by ksmurchison** [comment] 2018-02-23 16:44
It doesn't appear that the recent patches resolved the GSSAPI issue, so as far as I see it we are stuck between maintaining backwards compatibility and correctness per the spec.  Perhaps having a run-time configuration option to choose the behavior might be useful.  Thoughts?

**Comment by quanah** [comment] 2018-02-23 17:06
@ksmurchison  Ken Hornstein, one of the (at least at some point) IETF members of the Kerberos working group disputed the validity of the change that was made in 2.1.26 (See https://lists.andrew.cmu.edu/pipermail/cyrus-sasl/2015-April/002809.html).  This is already noted in #419.  In any case, I've asked @jaltman who is intimately involved with Kerberos (both MIT and Heimdal flavors) to take a look at the issue and provide feedback.  He won't be able to do so until the week of March 5th, however, due to his busy schedule.

**Comment by ksmurchison** [comment] 2018-02-23 17:09
@quanah  I like that plan.  I will also suggest to Alexey that he meet up with the Kerberos folks at IETF 101 the week of March 18 if need be.

**Comment by ksmurchison** [comment] 2018-04-20 14:33
Any feedback from the IETF folks?

**Comment by jaltman** [comment] 2018-04-22 02:49
Thanks for the reminder.   Ken Hornstein is correct and the portions of 080e51c7fa0421eb2f0210d34cf0ac48a228b1e9 that change the flags should be reverted; as it was proposed by https://github.com/cyrusimap/BugzillaImport/blob/master/attachments/1393/revert-flags.diff.  

The key thing to remember with GSS-API is that the input flags are not a requirement they are simply a request (or a hint) to prefer a mechanism that supports the requested options.   It is the responsibility of the client to verify when major_status == GSS_S_COMPLETE that the negotiated context properties meet the client's requirements.  

Its with that check that I believe cyrus sasl is in violation of the RFC.  The flags that are being checked are the ret_flags from gss_init_sec_context() which describe the capabilities of the mechanism not the properties of the negotiated context.   There is even a comment in the source code at plugins/gssapi.c line 1852 that reads " /* FIX ME: Should check the resulting flags here */".    The flag checks that are being performed at line 1806 against 'out_req_flags' should be performed against 'ctx_flags' output parameter of gss_inquire_context() because it is those flags that represent the properties of the negotiated security context.

**Comment by ksmurchison** [comment] 2018-06-01 20:21
I don't believe that we have had any negative feedback on the last RC.  Unless I hear objections, I will make the final release on Monday.

**Comment by quanah** [comment] 2018-06-01 20:55
@ksmurchison There was a follow up to the list that the SSF layer is reporting incorrectly.

**Comment by ksmurchison** [comment] 2018-06-01 20:57
Any patch, pull request or fix?

**Comment by quanah** [comment] 2018-06-01 20:58
@ksmurchison No, but it was one of the items that was advertised would be fixed in 2.1.27

**Comment by quanah** [comment] 2018-06-01 20:59
Link to message is: https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2018-May/004243.html

**Comment by quanah** [comment] 2018-11-27 19:11
This can be closed now, right @ksmurchison ? Since 2.1.27 has released. ;)

**Closed** 2018-11-27 19:21 UTC
Labels: P1
